model_config:
  trs:
    base_args:
      num_queries:
        hri_cls:
          resisc: 100
          aid: 100  # TODO: make decision
      share_decoders: true
      decoder_hidden_dim: 768
      dilation: true
      use_task_embedding_in_img_encoder: true
      use_task_embedding_in_lang_encoder: true
#      lr_backbone: 2e-7
      lr_backbone: 2e-6
    losses:
    - logit_bce
    # initialize the ResNet convnet backbone from DETR
    base_ckpt_path: https://dl.fbaipublicfiles.com/detr/detr-r50-dc5-f0fb7ef5.pth
    base_ckpt_load_backbone_only: true

evaluation:
  metrics:
  - type: accuracy
    key: accuracy
    datasets:
    - resisc
    - aid
#    params:
#      dataset_json_files:
#        dior:
#          val: ${env.data_dir}/datasets/DIOR/coco_ann/DIOR_val_coco.json
#          test: ${env.data_dir}/datasets/DIOR/coco_ann/DIOR_test_coco.json


optimizer:
  type: adam_w  # HuggingFace transformer's AdamW
  params:
#    lr: 1e-6
    lr: 1e-5
    eps: 1e-8
    weight_decay: 1e-4

scheduler:
  type: warmup_constant
  params:
    num_warmup_steps: 2000
#    num_training_steps: ${training.max_updates}

training:
  num_workers: 2
  # these are mostly the same as in COCO detection training
  clip_norm_mode: all
  clip_gradients: true
  max_grad_l2_norm: 0.1
  lr_scheduler: true
  lr_ratio: 0.1
  batch_size: 64
  max_updates: 200000
  checkpoint_interval: 10000
  evaluation_interval: 1000
  dataset_size_proportional_sampling: false
  early_stop:
    enabled: false
    criteria: resisc/accuracy
    minimize: false
  stdout_capture: false
  find_unused_parameters: true

checkpoint:
  max_to_keep: 5
