model_config:
  trs:
    base_ckpt_path: ''  # the initial DETR parameters to start from (this should be a checkpoint file trained w/ DETR package)
    base_ckpt_load_backbone_only: false
    detection_loss_weight: 1.

    loss_on_all_hs: false

    base_args:
      lr_backbone: 1e-4
      backbone: resnet50
      dilation: false
      position_embedding: sine
      enc_layers: 6
      dec_layers: 6
      dim_feedforward: 2048
      encoder_hidden_dim: 256
      dropout: 0.1
      nheads: 8
      # Override the config
      pre_norm: false
      pass_pos_and_query: true
      # detection losses
      aux_loss: true
      use_bcl: false
      set_cost_class: 1.
      set_cost_bbox: 5.
      set_cost_giou: 2.
      mask_loss_coef: 1.
      dice_loss_coef: 1.
      bbox_loss_coef: 5.
      giou_loss_coef: 2.
      attr_loss_coef: 1.
      eos_coef: 0.1
      # configs of multi-scale feature
      multi_scale:
        detection: true
        hri_cls: false
        hsi_cls: false
      num_feature_levels: 1
      # configs of deformable transformer encoder
      encoder_use_deformable_attention:
        detection: true
        hri_cls: false
        hsi_cls: false
      decoder_use_deformable_attention:
        detection: true
        hri_cls: false
        hsi_cls: false
      two_stage:
        detection: false  # ture
        hri_cls: false
        hsi_cls: false
      two_stage_num_proposals: 100
      # separate dimensionality for decoder
      decoder_hidden_dim: 256
      num_queries: {}
      share_decoders: false
      residual_in_encoder: true
      use_task_embedding_in_img_encoder: false
      use_task_embedding_in_lang_encoder: false
      # Visual Genome attribute data properties
      attribute_class_num: 401
      max_attribute_num: 16
      dropout_config: 0.1  # config for dropout out of the Transformer

    heads:
      detection:
        dior:
          task_idx: 0
          num_classes: 20
          use_attr: false
      hri_cls:
        resisc:
          task_idx: 1
          num_labels: 45
          loss_type: cross_entropy
        aid:
          task_idx: 2
          num_labels: 30
          loss_type: cross_entropy
      hsi_cls:
        indian:
          task_idx: 3
          num_labels: 16
          num_channels: 200
          loss_type: cross_entropy
        ksc:
          task_idx: 4
          num_labels: 16
          num_channels: 176
          loss_type: cross_entropy
        pavia:
          task_idx: 5
          num_labels: 9
          num_channels: 103
          loss_type: cross_entropy

    max_task_num: 256
    predict_attributes: false
